// Angular
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/forms';
import '@angular/router';
//import '@angular/http';
import '@angular/material';
import '@angular/material/core/theming/prebuilt/deeppurple-amber.css';
import 'rxjs';
import 'hammerjs';